using System.Runtime.CompilerServices;
namespace BacktestAnalyzer;
public sealed record AnalysisSample(DateTime Start,DateTime End,double Net,int Entries,double Lots,double Hours);
public sealed record AnalysisPanel(string Title,string Note,string Unit,List<(string Label,double A,double B,string Detail)> Values,bool Lines=false);
public static class AdvancedAnalysis
{
 static readonly ConditionalWeakTable<Report,List<AnalysisSample>> Cache=new();
 public static List<AnalysisSample> Samples(Report r)=>Cache.GetValue(r,q=>SeriesAnalysis.Selected(q).OrderBy(s=>s.End).Select(s=>new AnalysisSample(s.Start,s.End!.Value,(double)s.Net,s.Entries,(double)s.MaxGrossLots,ReportOptions.CycleSeconds(q,s)/3600)).ToList());
 static string L(string de,string en)=>Localization.English?en:de;
 public static double Correlation(double[] a,double[] b){if(a.Length!=b.Length||a.Length<2)return double.NaN;double ma=a.Average(),mb=b.Average(),cross=0,va=0,vb=0;for(int i=0;i<a.Length;i++){double da=a[i]-ma,db=b[i]-mb;cross+=da*db;va+=da*da;vb+=db*db;}return va*vb>0?cross/Math.Sqrt(va*vb):double.NaN;}
 public static AnalysisPanel Panel(Report r,ChartKind kind)
 {
  var samples=Samples(r);var money=DisplayFormat.Currency(r);string M(double v)=>DisplayFormat.Money((decimal)v,r);var values=new List<(string,double,double,string)>();string note="",unit=money;bool lines=false;
  switch(kind){
   case ChartKind.Concentration:
    var wins=samples.Where(s=>s.Net>0).OrderByDescending(s=>s.Net).ToList();double total=samples.Sum(s=>s.Net),gross=wins.Sum(s=>s.Net),sum=0;foreach(int n in new[]{0,1,5,10,Math.Max(1,(int)Math.Ceiling(wins.Count*.01))}.Distinct().Order()){sum=wins.Take(n).Sum(s=>s.Net);values.Add((n==0?L("Original","Original"):L("Ohne Top ","Without top ")+n,total-sum,sum,L("Entfernter Gewinn: ","Removed profit: ")+M(sum)+$"\n{(gross>0?100*sum/gross:0):N1} % "+L("aller Gewinne","of gross gains")));}note=L("Geschlossene Baskets/Trades · Sensitivität, kein neuer Backtest","Closed baskets/trades · sensitivity, not a rerun");break;
   case ChartKind.Streaks:
    var streaks=new List<(int Count,double Net,int Sign,DateTime Start,DateTime End)>();int count=0,sign=0;double net=0;DateTime begin=default,last=default;foreach(var s in samples){int next=Math.Sign(s.Net);if(next==0){if(count>0)streaks.Add((count,net,sign,begin,last));count=0;sign=0;continue;}if(next!=sign){if(count>0)streaks.Add((count,net,sign,begin,last));count=0;net=0;begin=s.Start;sign=next;}count++;net+=s.Net;last=s.End;}if(count>0)streaks.Add((count,net,sign,begin,last));foreach(var g in streaks.GroupBy(s=>s.Count).OrderBy(g=>g.Key).Take(24))values.Add((g.Key.ToString(),g.Count(s=>s.Sign>0),g.Count(s=>s.Sign<0),string.Join("\n",g.OrderBy(s=>s.Net).Take(3).Select(s=>$"{s.Start:dd.MM.yyyy} - {s.End:dd.MM.yyyy}: {M(s.Net)}"))));unit=L("Serienanzahl","Streak count");note=L("X: aufeinanderfolgende Ergebnisse · Blau Gewinn / Orange Verlust","X: consecutive outcomes · blue wins / orange losses");break;
   case ChartKind.Rolling:
    lines=true;int window=Math.Min(100,samples.Count);if(window>0){double rolling=0;for(int i=0;i<samples.Count;i++){rolling+=samples[i].Net;if(i>=window)rolling-=samples[i-window].Net;if(i+1>=window&&(i%Math.Max(1,samples.Count/80)==0||i==samples.Count-1)){var block=samples.Skip(i-window+1).Take(window).ToList();double gp=block.Where(s=>s.Net>0).Sum(s=>s.Net),gl=-block.Where(s=>s.Net<0).Sum(s=>s.Net);values.Add((samples[i].End.ToString("MM.yy"),rolling,0,$"{block[0].Start:yyyy-MM-dd} - {block[^1].End:yyyy-MM-dd}\nNetto: {M(rolling)}\n"+L("Trefferquote: ","Win rate: ")+$"{100d*block.Count(s=>s.Net>0)/window:N1} %\nPF: "+(gl>0?(gp/gl).ToString("N2"):"n/a")));}}note=L("Rollierendes Netto · letzte ","Rolling net · last ")+window+L(" Ergebnisse · Quote/PF im Mouseover"," outcomes · win rate/PF in tooltip");}break;
   case ChartKind.Underwater:
    var dd=EventDetails.Drawdowns(r,int.MaxValue);foreach(var ev in dd.OrderByDescending(e=>(e.Recovery??r.EquityPoints.Last().Time)-e.Start).Take(12)){double hours=((ev.Recovery??r.EquityPoints.Last().Time)-ev.Start).TotalHours;values.Add((ev.Start.ToString("MM.yy"),hours/24,0,EventDetails.Describe(r,ev)));}unit=L("Kalendertage","Calendar days");note=L("Längste Equity-Erholungsphasen · Kalenderdauer, inklusive Marktschließung","Longest equity recovery periods · calendar time, including closures");break;
   case ChartKind.Basket:
    foreach(var g in samples.GroupBy(s=>s.Entries<=1?"1":s.Entries<=3?"2-3":s.Entries<=10?"4-10":s.Entries<=30?"11-30":"31+").OrderBy(g=>g.Min(s=>s.Entries)))values.Add((g.Key,g.Count(s=>s.Net>=0),g.Count(s=>s.Net<0),$"n={g.Count()}\nNetto: {M(g.Sum(s=>s.Net))}\nLots max: {g.Max(s=>s.Lots):N2}\n"+L("Handelsstunden Ø: ","Trading hours mean: ")+$"{g.Average(s=>s.Hours):N2}"));unit=L("Anzahl","Count");note=L("Einstiegsanzahl je Basket/Trade · Lots und Dauer im Mouseover","Entry count per basket/trade · lots and duration in tooltip");break;
   case ChartKind.Costs:
    foreach(var g in r.Deals.GroupBy(d=>d.Symbol).OrderBy(g=>g.Key))values.Add((g.Key,-(double)g.Sum(d=>d.Commission+d.Fee),-(double)g.Sum(d=>d.Swap),L("Kommission + Fee: ","Commission + fee: ")+M((double)g.Sum(d=>d.Commission+d.Fee))+"\nSwap: "+M((double)g.Sum(d=>d.Swap))+"\nNetto: "+M((double)g.Sum(d=>d.Net))));note=L("Orange: Swap · Blau: Kommission · Violett: Gebühren. Oberhalb 0: Kosten; unterhalb 0: Gutschriften. Beträge unten mit Buchungsvorzeichen.","Blue: commission/fees · orange: swap · positive bars = expense");break;
   case ChartKind.Correlation:
    var symbols=SymbolAnalysis.Symbols(r);var dates=r.Deals.Select(d=>d.Time.Date).Distinct().Order().ToArray();var dailyNet=r.Deals.GroupBy(d=>(d.Symbol,d.Time.Date)).ToDictionary(g=>g.Key,g=>(double)g.Sum(d=>d.Net));foreach(var a in symbols.Take(12))foreach(var b in symbols.Take(12)){double[] aa=dates.Select(dt=>dailyNet.GetValueOrDefault((a,dt))).ToArray(),bb=dates.Select(dt=>dailyNet.GetValueOrDefault((b,dt))).ToArray();double corr=Correlation(aa,bb);values.Add((a+" / "+b,double.IsFinite(corr)?corr:0,0,double.IsFinite(corr)?$"r={corr:N3}\nn={dates.Length} "+L("Buchungstage","booking days"):L("Nicht definiert: konstante/fehlende Ergebnisse","Undefined: constant/missing outcomes")));}unit="r";note=L("Tägliche gebuchte Nettoergebnisse · fehlende Aktivität = 0 · keine Kurskorrelation","Daily booked net results · inactive = 0 · not price correlation");break;
   case ChartKind.Risk:
    var daily=DailyReturns(r);if(daily.Count>1){double mean=daily.Average(),sd=Math.Sqrt(daily.Sum(v=>Math.Pow(v-mean,2))/(daily.Count-1)),down=Math.Sqrt(daily.Sum(v=>Math.Pow(Math.Min(0,v),2))/daily.Count);var ddp=AccountCurves.EquityDrawdowns(r);double ulcer=ddp.Count>0?Math.Sqrt(ddp.Average(d=>Math.Pow((double)d.Percent,2))):double.NaN;values.Add(("Sharpe",sd>0?mean/sd*Math.Sqrt(252):0,0,L("Tagesrenditen · annualisiert √252 · risikofrei 0 %","Daily returns · annualized √252 · risk-free 0 %")));values.Add(("Sortino",down>0?mean/down*Math.Sqrt(252):0,0,L("Negative Tagesrenditen gegen 0 · √252","Negative daily returns against 0 · √252")));if(double.IsFinite(ulcer))values.Add(("Ulcer %",ulcer,0,L("Gespeicherte Equity-Punkte · nicht zeitgewichtet","Stored equity samples · not time weighted")));if(ddp.Count>0){double max=(double)ddp.Max(d=>d.Percent);double years=(r.Deals.Max(d=>d.Time)-r.Deals.Min(d=>d.Time)).TotalDays/365.25;double ending=(double)r.Balances.Last().Balance,initial=(double)r.InitialDeposit;if(initial>0&&ending>0&&years>0&&max>0)values.Add(("Calmar",(Math.Pow(ending/initial,1/years)-1)*100/max,0,"CAGR / Equity-DD"));}}unit="";note=L("Tagesrenditen aus Konto-Equity (sonst Ergebnislinie) · keine Ein-/Auszahlungen vorausgesetzt","Daily account-equity returns (otherwise result line) · assumes no cash flows");if(r.Deals.Any(d=>d.Symbol.Length==0))values.Clear();break;
   case ChartKind.Excursion:
    if(r.StrategyMode!="single"){
     foreach(var ex in BasketExcursions.Calculate(r))values.Add((ex.Start.ToString("dd.MM.yy"),(double)ex.MAE,(double)ex.MFE,$"{ex.Start:yyyy-MM-dd HH:mm:ss} - {ex.End:yyyy-MM-dd HH:mm:ss}\nMAE: {M((double)ex.MAE)} · MFE: {M((double)ex.MFE)}\nNetto: {M((double)ex.Net)}\n"+L("Tester-Beobachtungen: ","Tester samples: ")+ex.Observations+"\n"+L("Größte Beobachtungslücke: ","Largest observation gap: ")+Stats.Duration(ex.MaxGapSeconds)));
     note=L("Basket-Ergebnis = Tester-Equity minus Balance vor Start, inkl. realisierter Teilausstiege. Beobachtete Extrema; keine Tick-Extrema. Nur Baskets mit gespeicherten Punkten, keine Ein-/Auszahlungen.","Basket result = tester equity minus pre-entry balance, including realized partial closes. Observed extrema, not tick extrema. Sampled baskets only; no cash flows.");unit=money;break;}
    var bars=r.MarketBars.Select(b=>b with{Utc=MarketData.BrokerTime(r,b.Utc)}).OrderBy(b=>b.Utc).ToList();foreach(var trade in r.Closed.Where(t=>t.Symbol==r.MarketBrokerSymbol&&t.OpenPrice>0).Where((t,i)=>i%Math.Max(1,r.Closed.Count/100)==0)){var covered=bars.Where(b=>b.Utc>=trade.Open&&b.Utc.AddHours(1)<=trade.Close).ToList();if(covered.Count==0)continue;double mae=(double)(trade.Side=="buy"?Math.Max(0,trade.OpenPrice-covered.Min(b=>b.Low)):Math.Max(0,covered.Max(b=>b.High)-trade.OpenPrice))/ (double)trade.OpenPrice*100,mfe=(double)(trade.Side=="buy"?Math.Max(0,covered.Max(b=>b.High)-trade.OpenPrice):Math.Max(0,trade.OpenPrice-covered.Min(b=>b.Low)))/(double)trade.OpenPrice*100;values.Add((trade.Id,mae,mfe,$"{trade.Symbol} {trade.Side}\n{trade.Open:yyyy-MM-dd HH:mm} - {trade.Close:yyyy-MM-dd HH:mm}\nMAE: {mae:N3}% · MFE: {mfe:N3}%\nNetto: {M((double)trade.Net)}"));}unit="%";note=L("H1-Innenkerzen · Preisbewegung, keine exakten Tick-MAE/MFE · Randstunden ausgeschlossen","Interior H1 bars · price movement, not exact tick excursions · edge hours excluded");break;
   case ChartKind.MonteCarlo:
    var simulation=Simulate(r,600,12345);foreach(var q in new[]{.05,.25,.5,.75,.95})values.Add(($"P{q*100:0}",Quantile(simulation.Select(s=>s.Net),q),0,"Bootstrap · "+L("Nettoquantil","net quantile")+"\nDD P95: "+M(Quantile(simulation.Select(s=>s.DD),.95))+"\n"+L("Balance-Stillstand P95: ","Balance stagnation P95: ")+Quantile(simulation.Select(s=>(double)s.Duration),.95).ToString("N0")+L(" Handelsblöcke"," trading blocks")));note=L("600 Simulationen · ganze Tagesblöcke · realisierte Ergebnisse; kein intra-Basket Equity-DD","600 simulations · whole daily blocks · realized outcomes; no intra-basket equity DD");break;
   case ChartKind.Stress:
    double original=r.Deals.Sum(d=>(double)d.Net),lots=r.Deals.Where(d=>d.Entry is "in" or "inout").Sum(d=>(double)d.Volume);foreach(double fee in new[]{0d,1,2,5,10})values.Add((fee.ToString("0")+" "+money,original-fee*lots,fee*lots,L("Zusätzliche Kosten pro eröffnendem Lot: ","Extra costs per opening lot: ")+fee+" "+money+"\nNetto: "+M(original-fee*lots)));note=L("Kosten-Szenario pro Einstiegs-Lot · kein Ausführungs-/Slippage-Neubacktest","Cost scenario per opening lot · no execution/slippage rerun");break;
   case ChartKind.Regimes:
    var history=r.MarketBars.Select(b=>b with{Utc=MarketData.BrokerTime(r,b.Utc)}).OrderBy(b=>b.Utc).ToList();var grouped=new Dictionary<string,List<AnalysisSample>>();foreach(var s in samples){DateTime utc=s.Start;int at=history.BinarySearch(new MarketBar(utc,0,0,0,0),Comparer<MarketBar>.Create((a,b)=>a.Utc.CompareTo(b.Utc)));if(at<0)at=~at;int endIndex=at-1;while(endIndex>=0&&history[endIndex].Utc.AddHours(1)>utc)endIndex--;if(endIndex<24)continue;var past=history.Skip(endIndex-23).Take(24).ToArray();double move=(double)((past[^1].Close-past[0].Open)/past[0].Open)*100,vol=(double)past.Average(b=>(b.High-b.Low)/b.Open)*100;string label=move>.3?L("Aufwärts","Uptrend"):move<-.3?L("Abwärts","Downtrend"):L("Seitwärts","Sideways");label+=vol>.3?L(" / volatil"," / volatile"):L(" / ruhig"," / quiet");if(!grouped.ContainsKey(label))grouped[label]=new();grouped[label].Add(s);}foreach(var g in grouped)values.Add((g.Key,g.Value.Sum(s=>s.Net),0,$"n={g.Value.Count}\nØ: {M(g.Value.Average(s=>s.Net))}\n"+L("Trefferquote ","Win rate ")+$"{100d*g.Value.Count(s=>s.Net>0)/g.Value.Count:N1}%"));note=L("Netto aller Baskets nach Marktphase vor Einstieg. 24 H1: Trend ±0,3%; volatil = mittlere Spanne >0,3%. Heuristisch; Anzahl, Ø und Trefferquote im Mouseover.","Before entry: 24 completed H1 · trend ±0.3%, mean bar range 0.3% · heuristic");break;
   case ChartKind.StrategyGroups:
    string Reason(Deal d){string c=d.Comment.Trim().ToLowerInvariant();return c.StartsWith("tp ")||c.StartsWith("[tp")?"Take-Profit":c.StartsWith("sl ")||c.StartsWith("[sl")?"Stop-Loss":c.Contains("end of test")?L("Testende","Test end"):L("Sonstige Schließung","Other exit");}
    foreach(var g in r.Deals.Where(d=>d.Entry is "out" or "outby" or "out/by" or "inout").GroupBy(Reason))values.Add((g.Key,g.Sum(d=>(double)d.Net),0,$"n={g.Count():N0} "+L("Schließbuchungen","exit deals")+"\nNetto: "+M(g.Sum(d=>(double)d.Net))));note=L("Netto der Schließbuchungen nach exportiertem Kommentar (TP / SL / Testende / sonstige); keine EA-Trennung, Einstiegskosten nicht enthalten.","Exit-deal net by exported comment (TP / SL / test end / other); not EA separation, entry costs excluded.");break;
  }
  if(values.Count==0)note+=" · "+L("Nicht verfügbar mit diesen Daten","Unavailable with these data");return new(AdvancedPainter.Title(kind),note,unit,values,lines);
 }
 public static List<double> DailyReturns(Report r){var source=r.EquityPoints.Count>1?r.EquityPoints.Select(q=>(q.Time,q.Equity)):r.Balances.Select(q=>(q.Time,q.Balance));var daily=source.GroupBy(q=>q.Time.Date).OrderBy(g=>g.Key).Select(g=>g.OrderBy(q=>q.Time).Last().Item2).ToList();var result=new List<double>();for(int i=1;i<daily.Count;i++)if(daily[i-1]>0)result.Add((double)(daily[i]/daily[i-1]-1));return result;}
 public static double Quantile(IEnumerable<double> source,double q){var a=source.Order().ToArray();if(a.Length==0)return 0;double ix=q*(a.Length-1);int i=(int)ix;return a[i]+(a[Math.Min(a.Length-1,i+1)]-a[i])*(ix-i);}
 public static List<(double Net,double DD,int Duration)> Simulate(Report r,int runs,int seed){var blocks=Samples(r).GroupBy(s=>s.End.Date).Select(g=>g.OrderBy(s=>s.End).Select(s=>s.Net).ToArray()).ToArray();var output=new List<(double,double,int)>();if(blocks.Length==0)return output;var random=new Random(seed);for(int run=0;run<runs;run++){double balance=(double)r.InitialDeposit,peak=balance,maxDD=0;int flat=0,maxFlat=0;for(int i=0;i<blocks.Length;i++){foreach(double net in blocks[random.Next(blocks.Length)]){balance+=net;peak=Math.Max(peak,balance);maxDD=Math.Max(maxDD,peak-balance);}flat=balance<peak?flat+1:0;maxFlat=Math.Max(maxFlat,flat);}output.Add((balance-(double)r.InitialDeposit,maxDD,maxFlat));}return output;}
}
