namespace BacktestAnalyzer;
public static class AdvancedPainter
{
 public static readonly ChartKind[] Kinds={ChartKind.Concentration,ChartKind.Streaks,ChartKind.Rolling,ChartKind.Underwater,ChartKind.Basket,ChartKind.Costs,ChartKind.Correlation,ChartKind.Risk,ChartKind.Excursion,ChartKind.MonteCarlo,ChartKind.Stress,ChartKind.Regimes,ChartKind.StrategyGroups};
 public static string Title(ChartKind kind)=>(Localization.English?new[]{"Profit concentration","Winning / losing streaks","Rolling performance","Drawdown recovery time","Basket structure","Costs by symbol","Symbol correlation","Risk-adjusted metrics","MAE / MFE","Monte Carlo stress test","Cost scenarios","Market regimes","Strategy / comment groups"}:new[]{"Gewinnkonzentration","Gewinn- / Verlustserien","Rollierende Performance","Drawdown-Erholungsdauer","Basket-Aufbau","Kosten nach Symbol","Symbolkorrelation","Risikokennzahlen","MAE / MFE","Monte-Carlo-Stresstest","Kosten-Szenarien","Marktphasen","Strategie- / Kommentargruppen"})[Array.IndexOf(Kinds,kind)];
 public static void Draw(ICanvas c,ChartKind kind,Report r,Palette p,double x,double y,double width,double height)
 {
  var panel=AdvancedAnalysis.Panel(r,kind);c.Rect(x,y,width,height,p.Surface);c.Text(panel.Title,x+12,y+10,11,p.Ink,true);
  string line="";int row=0;foreach(var word in panel.Note.Split(' ')){var next=line+" "+word;if(c.Measure(next,5.5)>width-24&&line.Length>0){c.Text(line.Trim(),x+12,y+30+row++*7,5.5,p.Muted);line=word;}else line=next;}c.Text(line.Trim(),x+12,y+30+row*7,5.5,p.Muted);
  var vals=panel.Values;if(vals.Count==0)return;double left=x+58,right=x+width-15,top=y+58,bottom=y+height-44,w=right-left,h=bottom-top;
  if(kind==ChartKind.Correlation){int n=(int)Math.Sqrt(vals.Count);if(n<2){c.Text(Localization.English?"At least two symbols required":"Mindestens zwei Symbole erforderlich",left,top,9,p.Muted);return;}double cw=Math.Min(w/n,h/n);for(int i=0;i<n;i++){c.Text(vals[i*n].Label.Split(" / ")[0],left-42,top+i*cw+cw/2-3,6,p.Muted);c.Text(vals[i].Label.Split(" / ")[1],left+i*cw,top-9,6,p.Muted);for(int j=0;j<n;j++){var v=vals[i*n+j];double xx=left+j*cw,yy=top+i*cw;var col=ThemeSets.Blend(v.A>=0?p.Positive:p.Negative,p.Surface,Math.Abs(v.A));c.Rect(xx,yy,cw-1,cw-1,col);c.Text(v.Detail.StartsWith("r=")?v.A.ToString("0.00"):"n/a",xx+2,yy+cw/2-3,6,Math.Abs(v.A)>.65?p.Surface:p.Ink);c.Hover(xx,yy,cw-1,cw-1,v.Label+"\n"+v.Detail);}}return;}
  if(kind==ChartKind.Excursion){var ax=ChartAxis.Nice(0,Math.Max(.001,vals.Max(v=>v.A)),4);var ay=ChartAxis.Nice(0,Math.Max(.001,vals.Max(v=>v.B)),4);double XX(double v)=>left+w*v/ax.High;double YY(double v)=>bottom-h*v/ay.High;foreach(var v in ax.Ticks){c.Line(XX(v),top,XX(v),bottom,p.Line,.4);c.Text(v.ToString("0.##"),XX(v),bottom+4,6,p.Muted);}foreach(var v in ay.Ticks){c.Line(left,YY(v),right,YY(v),p.Line,.4);c.RightText(v.ToString("0.##"),left-3,YY(v)-3,6,p.Muted);}foreach(var v in vals){c.Circle(XX(v.A),YY(v.B),2,p.Positive);c.Hover(XX(v.A)-3,YY(v.B)-3,6,6,v.Detail);}c.Text("MAE (%)",left+w/2,bottom+18,6,p.Muted);c.VerticalText("MFE (%)",x+12,top+h/2,6,p.Muted);return;}
  var axis=ChartAxis.Nice(Math.Min(0,vals.Min(v=>Math.Min(v.A,v.B))),Math.Max(1,vals.Max(v=>Math.Max(v.A,v.B))),4);double Y(double v)=>bottom-(v-axis.Low)/(axis.High-axis.Low)*h;foreach(var tick in axis.Ticks){double yy=Y(tick);c.Line(left,yy,right,yy,p.Line,.4);c.RightText(ChartAxis.Number(tick)+(panel.Unit.Length>0?" "+panel.Unit:""),left-4,yy-3,6,p.Muted);}
  double bw=w/vals.Count;int stride=Math.Max(1,(int)Math.Ceiling(vals.Count/8d));for(int i=0;i<vals.Count;i++){var v=vals[i];double xx=left+i*bw;if(panel.Lines){if(i>0)c.Line(left+(i-.5)*bw,Y(vals[i-1].A),xx+bw/2,Y(v.A),p.Positive,.9);}else{c.Rect(xx+1,Math.Min(Y(v.A),Y(0)),Math.Max(.5,bw*.66-2),Math.Max(.5,Math.Abs(Y(v.A)-Y(0))),v.A>=0?p.Positive:p.Negative);if(v.B!=0)c.Rect(xx+bw*.68,Math.Min(Y(v.B),Y(0)),Math.Max(.5,bw*.3-1),Math.Max(.5,Math.Abs(Y(v.B)-Y(0))),p.Negative);}
   if(kind!=ChartKind.Excursion)c.Hover(xx,top,Math.Max(.5,bw-1),h,v.Label+"\n"+v.Detail+"\n"+v.A.ToString("N2")+" "+panel.Unit);
   if(kind!=ChartKind.Excursion&&(i%stride==0||i==vals.Count-1)){string label=v.Label.Length>22?v.Label[..21]+"…":v.Label;double size=5.5;if(c.Measure(label,size)>bw*stride-2&&kind!=ChartKind.Rolling){c.Text((i+1).ToString(),xx+bw/2,bottom+5,size,p.Muted);c.Hover(xx,bottom+3,bw,15,v.Label);}else c.Text(label,xx+1,bottom+5,size,p.Muted);}
  }
  if(kind==ChartKind.Excursion){c.Text("MAE (%) →",left,bottom+9,6,p.Muted);c.VerticalText("MFE (%)",x+10,(top+bottom)/2,6,p.Muted);}
  if(kind==ChartKind.MonteCarlo){var sim=AdvancedAnalysis.Simulate(r,600,12345);c.Text("DD P95: "+DisplayFormat.Money((decimal)AdvancedAnalysis.Quantile(sim.Select(s=>s.DD),.95),r)+" · "+(Localization.English?"Loss probability: ":"Verlustwahrscheinlichkeit: ")+(sim.Count>0?100d*sim.Count(s=>s.Net<0)/sim.Count:0).ToString("N1")+" %",left,y+height-13,6,p.Muted,true);}
 }
}
