namespace BacktestAnalyzer;
public static class AdvancedPainter
{
 public static readonly ChartKind[] Kinds={ChartKind.Concentration,ChartKind.Streaks,ChartKind.Rolling,ChartKind.Underwater,ChartKind.Basket,ChartKind.Costs,ChartKind.Correlation,ChartKind.Risk,ChartKind.Excursion,ChartKind.MonteCarlo,ChartKind.Stress,ChartKind.Regimes,ChartKind.StrategyGroups};
 public static string Title(ChartKind kind)=>(Localization.English?new[]{"Profit concentration","Winning / losing streaks","Rolling performance","Drawdown recovery time","Basket structure","Costs by symbol","Symbol correlation","Risk-adjusted metrics","MAE / MFE","Monte Carlo stress test","Cost scenarios","Market regimes","Results by exit reason"}:new[]{"Gewinnkonzentration","Gewinn- / Verlustserien","Rollierende Performance","Drawdown-Erholungsdauer","Basket-Aufbau","Kosten nach Symbol","Symbolkorrelation","Risikokennzahlen","MAE / MFE","Monte-Carlo-Stresstest","Kosten-Szenarien","Marktphasen","Ergebnisse nach Schließungsgrund"})[Array.IndexOf(Kinds,kind)];
 public static void Draw(ICanvas c,ChartKind kind,Report r,Palette p,double x,double y,double width,double height)
 {
  var panel=AdvancedAnalysis.Panel(r,kind);c.Rect(x,y,width,height,p.Surface);c.Text(panel.Title,x+12,y+10,11,p.Ink,true);
  string line="";int row=0;foreach(var word in panel.Note.Split(' ')){var next=line+" "+word;if(c.Measure(next,5.5)>width-24&&line.Length>0){c.Text(line.Trim(),x+12,y+30+row++*7,5.5,p.Muted);line=word;}else line=next;}c.Text(line.Trim(),x+12,y+30+row*7,5.5,p.Muted);
  var vals=panel.Values;if(vals.Count==0)return;double left=x+58,right=x+width-15,top=y+58,bottom=y+height-44,w=right-left,h=bottom-top;
  if(kind==ChartKind.Correlation){int n=(int)Math.Sqrt(vals.Count);if(n<2){c.Text(Localization.English?"At least two symbols required":"Mindestens zwei Symbole erforderlich",left,top,9,p.Muted);return;}double cw=Math.Min(w/n,h/n);for(int i=0;i<n;i++){c.RightText(vals[i*n].Label.Split(" / ")[0],left-6,top+i*cw+cw/2-3,6,p.Muted);c.Text(vals[i].Label.Split(" / ")[1],left+i*cw,top-9,6,p.Muted);for(int j=0;j<n;j++){var v=vals[i*n+j];double xx=left+j*cw,yy=top+i*cw;var col=ThemeSets.Blend(v.A>=0?p.Positive:p.Negative,p.Surface,Math.Abs(v.A));c.Rect(xx,yy,cw-1,cw-1,col);c.Text(v.Detail.StartsWith("r=")?v.A.ToString("0.00"):"n/a",xx+2,yy+cw/2-3,6,Math.Abs(v.A)>.65?p.Surface:p.Ink);c.Hover(xx,yy,cw-1,cw-1,v.Label+"\n"+v.Detail);}}return;}
  if(kind==ChartKind.Costs){
   var groups=r.Deals.GroupBy(d=>d.Symbol).Where(g=>g.Key.Length>0).ToArray();var rows=groups.Select(g=>new{Symbol=g.Key,Swap=-g.Sum(d=>d.Swap),Commission=-g.Sum(d=>d.Commission),Fee=-g.Sum(d=>d.Fee)}).ToArray();if(rows.Length==0)return;
   bool feeKnown=r.AvailableColumns.Contains("fee");var colors=new[]{p.Negative,p.Positive,p.Dark?"#CDA0FF":"#8245B5"};var axisC=ChartAxis.Nice(Math.Min(0,rows.Min(q=>new[]{q.Swap,q.Commission,q.Fee}.Where(v=>v<0).Sum()) is decimal mn?(double)mn:0),Math.Max(1,(double)rows.Max(q=>new[]{q.Swap,q.Commission,q.Fee}.Where(v=>v>0).Sum())),4);double baseBottom=y+height-68;double CY(decimal v)=>baseBottom-((double)v-axisC.Low)/(axisC.High-axisC.Low)*(baseBottom-top);foreach(var tick in axisC.Ticks){c.Line(left,CY((decimal)tick),right,CY((decimal)tick),p.Line,.55);c.RightText(ChartAxis.Number(tick)+" "+DisplayFormat.Currency(r),left-4,CY((decimal)tick)-3,6,p.Muted);}double slot=w/rows.Length;
   for(int i=0;i<rows.Length;i++){var q=rows[i];double center=left+(i+.5)*slot;decimal plus=0,minus=0;var costs=new[]{q.Swap,q.Commission,q.Fee};for(int j=0;j<3;j++){decimal start=costs[j]>=0?plus:minus,end=start+costs[j];c.Rect(center-slot*.3,Math.Min(CY(start),CY(end)),slot*.6,Math.Abs(CY(end)-CY(start)),colors[j]);if(costs[j]>=0)plus=end;else minus=end;}string detail=q.Symbol+"\nSwap: "+DisplayFormat.Money(-q.Swap,r)+"\nKommission: "+DisplayFormat.Money(-q.Commission,r)+"\nGebühren: "+(feeKnown?DisplayFormat.Money(-q.Fee,r):"nicht exportiert")+"\nBekannte Kosten netto: "+DisplayFormat.Money(q.Swap+q.Commission+q.Fee,r);c.Hover(center-slot*.4,top,slot*.8,baseBottom-top,detail);c.CenterText(q.Symbol,center,baseBottom+4,6,p.Muted);for(int j=0;j<3;j++)c.CenterText(new[]{"Swap: ","Komm.: ","Fee: "}[j]+(j==2&&!feeKnown?"nicht exportiert":DisplayFormat.Money(-costs[j],r)),center,baseBottom+15+j*8,5.5,colors[j]);c.CenterText("Bekannte Kosten: "+DisplayFormat.Money(q.Swap+q.Commission+q.Fee,r),center,baseBottom+40,5.5,p.Ink,true);}return;
  }
  if(kind==ChartKind.Excursion){var ax=ChartAxis.Nice(0,Math.Max(.001,vals.Max(v=>v.A)),4);var ay=ChartAxis.Nice(0,Math.Max(.001,vals.Max(v=>v.B)),4);double XX(double v)=>left+w*v/ax.High;double YY(double v)=>bottom-h*v/ay.High;foreach(var v in ax.Ticks){c.Line(XX(v),top,XX(v),bottom,p.Line,.4);var label=ChartAxis.Number(v)+" "+panel.Unit;c.CenterText(label,Math.Clamp(XX(v),left+c.Measure(label,6)/2,right-c.Measure(label,6)/2),bottom+4,6,p.Muted);}foreach(var v in ay.Ticks){c.Line(left,YY(v),right,YY(v),p.Line,.4);c.RightText(ChartAxis.Number(v)+" "+panel.Unit,left-3,YY(v)-3,6,p.Muted);}foreach(var group in vals.GroupBy(v=>((int)((XX(v.A)-left)/3),(int)((YY(v.B)-top)/3)))){var v=group.First();c.Circle(XX(v.A),YY(v.B),1.3,p.Positive);}foreach(var group in vals.GroupBy(v=>(Math.Min(11,(int)(12*v.A/ax.High)),Math.Min(7,(int)(8*v.B/ay.High))))){double gx=left+group.Key.Item1*w/12,gy=bottom-(group.Key.Item2+1)*h/8;string detail=$"n={group.Count():N0}\nMAE: {group.Min(v=>v.A):N2} - {group.Max(v=>v.A):N2} {panel.Unit}\nMFE: {group.Min(v=>v.B):N2} - {group.Max(v=>v.B):N2} {panel.Unit}\n"+group.OrderByDescending(v=>v.A).First().Detail;c.Hover(gx,gy,w/12,h/8,detail);}c.Text($"n={vals.Count:N0} "+(Localization.English?"sampled baskets/trades":"Baskets/Trades mit Beobachtungen"),left,y+height-12,5.5,p.Muted);c.Text("MAE ("+panel.Unit+")",left+w/2,bottom+18,6,p.Muted);c.VerticalText("MFE ("+panel.Unit+")",x+12,top+h/2,6,p.Muted);return;}
  var axis=ChartAxis.Nice(Math.Min(0,vals.Min(v=>Math.Min(v.A,v.B))),Math.Max(1,vals.Max(v=>Math.Max(v.A,v.B))),4);double Y(double v)=>bottom-(v-axis.Low)/(axis.High-axis.Low)*h;foreach(var tick in axis.Ticks){double yy=Y(tick);c.Line(left,yy,right,yy,p.Line,.4);c.RightText(ChartAxis.Number(tick)+(panel.Unit.Length>0?" "+panel.Unit:""),left-4,yy-3,6,p.Muted);}
  double bw=w/vals.Count;int stride=Math.Max(1,(int)Math.Ceiling(vals.Count/8d));for(int i=0;i<vals.Count;i++){var v=vals[i];double xx=left+i*bw;if(panel.Lines){if(i>0)c.Line(left+(i-.5)*bw,Y(vals[i-1].A),xx+bw/2,Y(v.A),p.Positive,.9);}else{c.Rect(xx+bw*.1,Math.Min(Y(v.A),Y(0)),Math.Max(.5,bw*(v.B==0?.8:.55)-2),Math.Max(.5,Math.Abs(Y(v.A)-Y(0))),v.A>=0?p.Positive:p.Negative);if(v.B!=0)c.Rect(xx+bw*.68,Math.Min(Y(v.B),Y(0)),Math.Max(.5,bw*.22-1),Math.Max(.5,Math.Abs(Y(v.B)-Y(0))),p.Negative);}
   if(kind!=ChartKind.Excursion)c.Hover(xx,top,Math.Max(.5,bw-1),h,v.Label+"\n"+v.Detail+"\n"+v.A.ToString("N2")+" "+panel.Unit);
   if(!panel.Lines&&bw>=60&&panel.Unit==DisplayFormat.Currency(r))c.CenterText("Netto: "+DisplayFormat.Money((decimal)v.A,r),xx+bw/2,bottom+17,5.5,p.Ink,true);
   if(kind!=ChartKind.Excursion&&(i%stride==0||i==vals.Count-1)){string label=v.Label.Length>22?v.Label[..21]+"…":v.Label;double size=5.5;if(c.Measure(label,size)>bw*stride-2&&kind!=ChartKind.Rolling){c.Text((i+1).ToString(),xx+bw/2,bottom+5,size,p.Muted);c.Hover(xx,bottom+3,bw,15,v.Label);}else c.CenterText(label,xx+bw/2,bottom+5,size,p.Muted);}
  }

  var last=SeriesAnalysis.Selected(r).LastOrDefault(c=>SeriesAnalysis.TestEnd(r,c));if(last!=null&&(kind==ChartKind.Rolling||kind==ChartKind.Concentration)){string label=(Localization.English?"Forced close: ":"Zwangsschluss: ")+last.Start.ToString("dd.MM.yy HH:mm")+" → "+last.End!.Value.ToString("dd.MM.yy HH:mm");c.Text(label,left,y+height-15,5.5,p.Negative);c.Hover(left,y+height-17,w,13,label+"\nNetto: "+DisplayFormat.Money(last.Net,r));if(kind==ChartKind.Rolling)c.Circle(right-bw/2,Y(vals[^1].A),2,p.Negative);}
  if(kind==ChartKind.MonteCarlo){var sim=AdvancedAnalysis.Simulate(r,600,12345);c.Text("DD P95: "+DisplayFormat.Money((decimal)AdvancedAnalysis.Quantile(sim.Select(s=>s.DD),.95),r)+" · "+(Localization.English?"Loss probability: ":"Verlustwahrscheinlichkeit: ")+(sim.Count>0?100d*sim.Count(s=>s.Net<0)/sim.Count:0).ToString("N1")+" %",left,y+height-13,6,p.Muted,true);}
 }
}
