using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace BacktestAnalyzer;
public sealed partial class MainWindow
{
 UIElement ColorSettings(){var panel=new StackPanel{Margin=new Thickness(20)};panel.Children.Add(Text(Localization.English?"Saved light/dark color sets":"Gespeicherte Light-/Dark-Farbsets",18,true));panel.Children.Add(Select(new[]{"Standard"}.Concat(ThemeSets.Sets.Keys),ThemeSets.Active,v=>{ThemeSets.Activate(v);if(panel.Parent is ScrollViewer host)host.Content=ColorSettings();}));var name=Field(ThemeSets.Active=="Standard"?"Mein Farbset":ThemeSets.Active);panel.Children.Add(name);var fields=new Dictionary<string,TextBox>();foreach(bool dark in new[]{false,true}){panel.Children.Add(Text(dark?"Dark":"Light",16,true));var p=new Palette(dark);foreach(var key in new[]{"Positive","Negative","Background","Surface"}){var row=new WrapPanel();row.Children.Add(Text(key=="Positive"?"Balance / Gewinn / Buy":key=="Negative"?"DD / Verlust / Sell":key,12));string value=key=="Positive"?p.Positive:key=="Negative"?p.Negative:key=="Background"?p.Background:p.Surface;var field=Field(value);field.Width=110;fields[(dark?"Dark.":"Light.")+key]=field;row.Children.Add(field);var swatch=new Border{Width=40,Height=30,Background=B(value),Margin=new Thickness(8)};row.Children.Add(swatch);row.Children.Add(Button(Localization.English?"Choose":"Wählen",()=>{var picker=new Window{Owner=this,Title="Farbe / Color",Width=350,Height=240,WindowStartupLocation=WindowStartupLocation.CenterOwner};var choices=new WrapPanel();foreach(var hex in new[]{"#113B65","#76B7FF","#C87500","#FFB348","#16804A","#66D7A9","#8245B5","#CDA0FF","#BF2362","#FF7DA7","#101B2B","#19273B","#F2F5F9","#FFFFFF"}){var choice=new System.Windows.Controls.Button{Width=55,Height=45,Background=B(hex),ToolTip=hex,Margin=new Thickness(3)};choice.Click+=(_,_)=>{field.Text=hex;swatch.Background=B(hex);picker.Close();};choices.Children.Add(choice);}picker.Content=choices;picker.ShowDialog();}));panel.Children.Add(row);}}
 panel.Children.Add(Text(Localization.English?"Curve fills are derived automatically from line color and surface brightness.":"Kurvenflächen werden automatisch aus Linienfarbe und Hintergrundhelligkeit abgeleitet.",11));panel.Children.Add(Button(Localization.English?"Save & apply set":"Farbset speichern & anwenden",()=>{try{ThemeSets.Save(name.Text,fields.ToDictionary(k=>k.Key,k=>k.Value.Text));Render();}catch(Exception e){MessageBox.Show(e.Message);}},true));return panel;}
}
