using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
namespace BacktestAnalyzer;
public sealed class ComparisonWindow:Window
{
 Report? a,b;readonly bool dark;bool normalized=true,elapsed=true;string curve="Balance";StackPanel content=new();
 public ComparisonWindow(Report? current,bool isDark){a=current;dark=isDark;Title=Localization.T("Backtest-Vergleich");Width=1300;Height=950;Render();}
 void Load(bool first){var pick=new OpenFileDialog{Filter="Backtest / Analyse|*.html;*.htm;*.xlsx;*.tst;*.bta"};if(pick.ShowDialog()!=true)return;try{var r=AnalysisFile.Load(pick.FileName);if(first)a=r;else b=r;Render();}catch(Exception e){MessageBox.Show(e.Message);}}
 TextBlock Text(string value,int size=13)=>new(){Text=Localization.T(value),FontSize=size,Foreground=new SolidColorBrush((Color)ColorConverter.ConvertFromString(new Palette(dark).Ink)),TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,4,0,4)};
 void Render(){var palette=new Palette(dark);Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString(palette.Background));content=new StackPanel{Margin=new Thickness(24)};Content=new ScrollViewer{Content=content};var buttons=new WrapPanel();void Button(string text,Action action){var button=new Button{Content=Localization.T(text),Padding=new Thickness(14,8,14,8),Margin=new Thickness(0,0,10,8)};button.Click+=(_,_)=>action();buttons.Children.Add(button);}Button("Backtest A laden",()=>Load(true));Button("Backtest B laden",()=>Load(false));Button(normalized?"Kurven: Startwert 100":"Kurven: Kontowährung",()=>{normalized=!normalized;Render();});Button(elapsed?"Zeit: seit Testbeginn":"Zeit: Kalenderdatum",()=>{elapsed=!elapsed;Render();});Button("Kurve: "+curve,()=>{curve=curve=="Balance"?"Equity":curve=="Equity"?"Drawdown":"Balance";Render();});content.Children.Add(buttons);
  content.Children.Add(Text("A: "+(a?.Strategy??"—")));content.Children.Add(Text("B: "+(b?.Strategy??"—")));if(a==null||b==null)return;
  content.Children.Add(Text("A: "+Period(a)+" · "+a.Find("Währung","Currency")+" · Start "+DisplayFormat.Money(a.InitialDeposit,a)));content.Children.Add(Text("B: "+Period(b)+" · "+b.Find("Währung","Currency")+" · Start "+DisplayFormat.Money(b.InitialDeposit,b)));
  if(a.Find("Währung","Currency")!=b.Find("Währung","Currency")){normalized=true;content.Children.Add(Text("Unterschiedliche Kontowährungen: Geldbeträge ohne Währungsumrechnung nicht direkt vergleichbar."));}
  var sa=StatsFor(a);var sb=StatsFor(b);var rows=new List<ComparisonRow>();void Metric(string label,double av,double bv,string unit=""){double delta=bv-av;rows.Add(new(label,Format(av,unit,a),Format(bv,unit,b),unit=="money"&&a.Find("Währung","Currency")!=b.Find("Währung","Currency")?"—":delta.ToString("+0.##;-0.##;0",Localization.Culture)+(unit=="money"?" "+DisplayFormat.Currency(a):" "+unit),av==0?"—":(delta/Math.Abs(av)*100).ToString("+0.##;-0.##;0",Localization.Culture)+" %"));}
  Metric("Netto",(double)a.Deals.Sum(d=>d.Net),(double)b.Deals.Sum(d=>d.Net),"money");Metric("Abgeschlossene Trades",sa.Count,sb.Count);Metric("Durchschnittliche Handelsdauer",sa.Mean/3600,sb.Mean/3600,"h");Metric("Mittlere Haltezeit (50 %)",sa.Median/3600,sb.Median/3600,"h");Metric("Längste Haltezeit",sa.Max/3600,sb.Max/3600,"h");Metric("Swap",(double)a.Deals.Sum(d=>d.Swap),(double)b.Deals.Sum(d=>d.Swap),"money");Metric("Kommission",(double)a.Deals.Sum(d=>d.Commission),(double)b.Deals.Sum(d=>d.Commission),"money");Metric("Gehandelte Lots",(double)a.Closed.Sum(t=>t.Volume),(double)b.Closed.Sum(t=>t.Volume),"Lots");var ad=AccountCurves.EquityDrawdowns(a);var bd=AccountCurves.EquityDrawdowns(b);if(ad.Count>0&&bd.Count>0)Metric("Equity-DD Max",(double)ad.Max(d=>d.Percent),(double)bd.Max(d=>d.Percent),"%");else rows.Add(new("Equity-DD Max",ad.Count>0?ad.Max(d=>d.Percent).ToString("N2")+" %":"nicht verfügbar",bd.Count>0?bd.Max(d=>d.Percent).ToString("N2")+" %":"nicht verfügbar","—","—"));
  var grid=new DataGrid{ItemsSource=rows,AutoGenerateColumns=true,IsReadOnly=true,CanUserAddRows=false,Height=330};content.Children.Add(grid);content.Children.Add(new ComparisonPlot{A=a,B=b,Palette=palette,Normalized=normalized,Elapsed=elapsed,Mode=curve,Height=280});
  content.Children.Add(Text("Haltezeitverteilungen: A links / B rechts",16));var charts=new WrapPanel();charts.Children.Add(new ChartView{Report=a,Trades=a.Closed,Palette=palette,Kind=ChartKind.Histogram,Width=580,Height=270});charts.Children.Add(new ChartView{Report=b,Trades=b.Closed,Palette=palette,Kind=ChartKind.Histogram,Width=580,Height=270});content.Children.Add(charts);
  content.Children.Add(Text("Jahresergebnisse",16));content.Children.Add(new DataGrid{ItemsSource=a.Deals.Select(d=>d.Time.Year).Union(b.Deals.Select(d=>d.Time.Year)).Order().Select(year=>new{Jahr=year,A=DisplayFormat.Money(a.Deals.Where(d=>d.Time.Year==year).Sum(d=>d.Net),a),B=DisplayFormat.Money(b.Deals.Where(d=>d.Time.Year==year).Sum(d=>d.Net),b)}).ToList(),IsReadOnly=true,Height=140});
  content.Children.Add(Text("Monatsergebnisse",16));var months=a.Deals.Select(d=>d.Time.ToString("yyyy-MM")).Union(b.Deals.Select(d=>d.Time.ToString("yyyy-MM"))).Order();content.Children.Add(new DataGrid{ItemsSource=months.Select(m=>new{Monat=m,A=DisplayFormat.Money(a.Deals.Where(d=>d.Time.ToString("yyyy-MM")==m).Sum(d=>d.Net),a),B=DisplayFormat.Money(b.Deals.Where(d=>d.Time.ToString("yyyy-MM")==m).Sum(d=>d.Net),b)}).ToList(),IsReadOnly=true,Height=260});
  content.Children.Add(Text("Unterschiedliche Strategieparameter",16));var ap=Parameters(a);var bp=Parameters(b);foreach(var key in ap.Keys.Union(bp.Keys).Where(k=>ap.GetValueOrDefault(k)!=bp.GetValueOrDefault(k)))content.Children.Add(Text(key+": A = "+ap.GetValueOrDefault(key,"—")+" | B = "+bp.GetValueOrDefault(key,"—")));
 }
 static Dictionary<string,string> Parameters(Report r)=>r.InputParameters.Where(p=>p.Contains('=')).Select(p=>p.Split('=',2)).GroupBy(p=>p[0]).ToDictionary(g=>g.Key,g=>g.Last()[1]);
 static string Period(Report r)=>r.Deals.Count==0?"—":DisplayFormat.Time(r.Deals.Min(d=>d.Time))+" – "+DisplayFormat.Time(r.Deals.Max(d=>d.Time));
 static Stats StatsFor(Report r)=>new(r.Closed,r.ExcludeWeekends,r.SaturdayTrading,r.SundayTrading,r.NightPauseMinutes,r.NightPauseStartMinute);
 static string Format(double v,string unit,Report r)=>unit=="money"?DisplayFormat.Money((decimal)v,r):v.ToString("N2",Localization.Culture)+" "+unit;
 record ComparisonRow(string Kennzahl,string A,string B,string Differenz,string Prozent);
}
public sealed class ComparisonPlot:FrameworkElement
{
 public required Report A{get;init;}public required Report B{get;init;}public required Palette Palette{get;init;}public string Mode{get;init;}="Balance";public bool Normalized{get;init;}public bool Elapsed{get;init;}
 protected override void OnRender(DrawingContext dc){var c=new WpfCanvas(dc);double w=ActualWidth,h=ActualHeight,left=90,right=w-20,top=45,bottom=h-30;c.Rect(0,0,w,h,Palette.Surface);c.Text(Mode+"-Vergleich · A: Blau / B: Orange",12,10,13,Palette.Ink,true);List<(DateTime Time,decimal Balance)> Values(Report r)=>Mode=="Balance"?AccountCurves.DisplayBalances(r):Mode=="Equity"?r.EquityPoints.Select(p=>(p.Time,p.Equity)).ToList():AccountCurves.EquityDrawdowns(r).Select(p=>(p.Time,-p.Percent)).ToList();var av=Values(A);var bv=Values(B);if(av.Count<2||bv.Count<2)return;double Value(decimal v,Report r)=>Mode=="Drawdown"?(double)v:Normalized?(r.InitialDeposit==0?0:(double)(v/r.InitialDeposit*100)):(double)v;var axis=ChartAxis.Nice(av.Select(p=>Value(p.Balance,A)).Concat(bv.Select(p=>Value(p.Balance,B))).Min(),av.Select(p=>Value(p.Balance,A)).Concat(bv.Select(p=>Value(p.Balance,B))).Max());var start=av[0].Time<bv[0].Time?av[0].Time:bv[0].Time;double span=Elapsed?Math.Max((av[^1].Time-av[0].Time).TotalSeconds,(bv[^1].Time-bv[0].Time).TotalSeconds):Math.Max((av[^1].Time-start).TotalSeconds,(bv[^1].Time-start).TotalSeconds);span=Math.Max(1,span);foreach(var tick in axis.Ticks){double yy=bottom-(tick-axis.Low)/(axis.High-axis.Low)*(bottom-top);c.Line(left,yy,right,yy,Palette.Line);c.Text(ChartAxis.Number(tick)+(Mode=="Drawdown"?" %":Normalized?"":" "+DisplayFormat.Currency(A)),10,yy-4,8,Palette.Muted);}void Draw(List<(DateTime Time,decimal Balance)> data,Report r,string color){int stride=Math.Max(1,data.Count/2000);double X(DateTime t)=>left+(t-(Elapsed?data[0].Time:start)).TotalSeconds/span*(right-left);double Y(decimal v)=>bottom-(Value(v,r)-axis.Low)/(axis.High-axis.Low)*(bottom-top);for(int i=stride;i<data.Count;i+=stride)c.Line(X(data[i-stride].Time),Y(data[i-stride].Balance),X(data[i].Time),Y(data[i].Balance),color,1);}Draw(av,A,Palette.Positive);Draw(bv,B,Palette.Negative);}
}
