namespace BacktestAnalyzer;
public sealed record ExposurePoint(DateTime Time,int Buy,int Sell,decimal BuyLots,decimal SellLots);
public static class Exposure
{
 static readonly System.Runtime.CompilerServices.ConditionalWeakTable<Report,List<ExposurePoint>> Cache=new();
 public static List<ExposurePoint> Points(Report r)=>Cache.GetValue(r,Build);
 static List<ExposurePoint> Build(Report r){var history=r.FullHistory.Count>0?r.FullHistory:r.Deals;if(history.Where(d=>d.Entry is "in" or "out" or "inout" or "outby").Any(d=>d.Position.Length==0)){var fallback=new List<ExposurePoint>();decimal buy=0,sell=0;foreach(var batch in history.OrderBy(d=>d.Time).GroupBy(d=>d.Time)){foreach(var d in batch){if(d.Entry=="in"){if(d.Side=="buy")buy+=d.Volume;else sell+=d.Volume;}else if(d.Entry is "out" or "outby" or "out/by"){if(d.Side=="sell")buy-=d.Volume;else sell-=d.Volume;}else if(d.Entry is "inout" or "in/out"){if(d.Side=="sell"){var used=Math.Min(buy,d.Volume);buy-=used;sell+=d.Volume-used;}else{var used=Math.Min(sell,d.Volume);sell-=used;buy+=d.Volume-used;}}}fallback.Add(new(batch.Key,-1,-1,buy,sell));}return fallback;}var result=new List<ExposurePoint>();var positions=new Dictionary<string,(string Side,decimal Lots)>();foreach(var batch in (r.FullHistory.Count>0?r.FullHistory:r.Deals).OrderBy(d=>d.Time).GroupBy(d=>d.Time)){foreach(var d in batch){string key=d.Position.Length>0?d.Symbol+":"+d.Position:"order:"+d.Order;if(d.Entry=="in"){var old=positions.GetValueOrDefault(key);positions[key]=(d.Side,old.Lots+d.Volume);}else if(d.Entry is "out" or "outby" or "out/by"){if(positions.TryGetValue(key,out var old)){decimal volume=old.Lots-d.Volume;if(volume<=0)positions.Remove(key);else positions[key]=(old.Side,volume);}}else if(d.Entry is "inout" or "in/out"){var old=positions.GetValueOrDefault(key);decimal remain=d.Volume-old.Lots;if(remain>0)positions[key]=(d.Side,remain);else if(remain<0)positions[key]=(old.Side,-remain);else positions.Remove(key);}}result.Add(new(batch.Key,positions.Count(p=>p.Value.Side=="buy"),positions.Count(p=>p.Value.Side=="sell"),positions.Where(p=>p.Value.Side=="buy").Sum(p=>p.Value.Lots),positions.Where(p=>p.Value.Side=="sell").Sum(p=>p.Value.Lots)));}return result;}
 public static ExposurePoint At(Report r,DateTime time){var values=Points(r);int lo=0,hi=values.Count-1,best=-1;while(lo<=hi){int mid=(lo+hi)/2;if(values[mid].Time<=time){best=mid;lo=mid+1;}else hi=mid-1;}return best>=0?values[best]:new(time,0,0,r.OpeningBuyLots,r.OpeningSellLots);}
 public static string Text(Report r,DateTime time){var p=At(r,time);bool exact=r.Deals.Where(d=>d.Entry is "in" or "out" or "inout" or "outby").All(d=>d.Position.Length>0);return (exact?$"Offene Positionen: {p.Buy+p.Sell} · Buy {p.Buy} / Sell {p.Sell}":"Offene Positionsanzahl: ohne vollständige IDs nicht gesichert")+$"\nOffene Lots: {p.BuyLots+p.SellLots:N2} · Buy {p.BuyLots:N2} / Sell {p.SellLots:N2}";}
}
