namespace BacktestAnalyzer;
public static class HelpContent
{
 public static List<(string Title,string Body)> Sections(Report r)=>Localization.English?new(){
 ("Sources and scope","Backtest and account-history HTML/XLSX retain their exported transactions. Original metrics are formatted for display without replacing their source values. Position IDs take precedence; ambiguous matching is identified. Annual trade statistics use closing-year cohorts; booked monthly results use transaction dates."),
 ("Profit, costs and cash flows","Deal net = profit + commission + swap + fee, using signed exported amounts. Deposits, withdrawals, credit/bonus and other non-trade bookings are retained separately and never counted as trading profit. Balance = opening balance + trade net + balance-affecting bookings; credit affects equity, not balance. Separately booked commissions, fees and interest remain part of trading results, not external cash flows. Unknown separate fees are not assumed zero. The cash-flow-adjusted result line removes account bookings from raw balance."),
 ("Returns and drawdown","Daily cash-flow-adjusted returns use Modified Dietz: (ending value - beginning value - net flows) / (beginning value + time-weighted flows). Flow weight is remaining fraction of the interval. Zero/nonpositive denominators are omitted. Cash-flow-adjusted drawdown uses value minus cumulative flows: DD = previous peak - current adjusted value; DD% = DD / positive adjusted peak × 100. Raw account balance remains visible separately. Incomplete exports prevent reliable reconstruction."),
 ("Holding duration and quantiles","Calendar duration = final close - entry. Trading duration subtracts configured closed weekdays and the assumed overnight break; holidays are not inferred. Partial closes use volume-weighted elapsed time for the weighted metric. Mean = sum/n; sample standard deviation uses n-1. Displayed 'within' thresholds use the observed nearest rank ceil(p×n), rounded upward to whole seconds. 100% is the longest observed duration. Open trades do not enter closed-duration statistics."),
 ("Cycles and test-end closures","A basket cycle runs from the first entry until all account positions close. Single-trade mode uses position/order matching. Test-end forced closure is identified from source comments; an account-history end alone is not a forced close. The final forced entry, last regular closure and actual forced end are marked on chronological charts. Actual losses remain in totals; the separately labeled adjusted view excludes the identified final forced cycle."),
 ("Equity, market data and display","Equity observations come from original tester cache when available, not from estimated closed-trade equity. Balance display groups bookings in configured windows; calculations retain source transactions. Market candles use confirmed broker time rules and their price currency. Equity drawdown compares equity to its previous peak. Equity below balance is an equity/balance shortfall; credit and other adjustments can make it differ from unrealized loss."),
 ("MAE / MFE","For sampled baskets, basket result = stored tester equity - balance immediately before entry, including realized partial exits and costs. MAE = max(0, -minimum observed basket result); MFE = max(0, maximum observed basket result). Zero and final net are included; a basket must contain observations. Sampling gaps appear in tooltips. These are observed extrema, not exact tick extrema. Single-trade H1 analysis uses only fully covered interior bars and measures percentage price movement, not monetary tick excursions."),
 ("Time patterns and charts","Heatmaps use the exact weekday/hour cell. Long-duration share = closed regular cycles above threshold / all regular starts in that cell × 100; >24 h uses the same duration basis. Forced-end cycles are excluded from this ratio. Profit/loss stacked bars show gross gains plus absolute losses, not net height. Broad bars show signed gains, losses and net; narrow bars show net in hover."),
 ("Risk metrics","Profit factor = positive net / absolute negative net; undefined without losses. Win rate = winning closed observations / all closed observations. Sharpe = mean daily return / sample standard deviation × √252, risk-free 0. Sortino uses downside deviation against 0 × √252. Ulcer index = sqrt(mean squared stored DD%), not time-weighted. Calmar = CAGR / maximum equity DD; omitted with cash flows when reliable CAGR is unavailable."),
 ("Sensitivity and simulations","Concentration removes the largest winning outcomes as sensitivity only. Monte Carlo resamples complete daily realized-result blocks with replacement, 600 runs, deterministic seed 12345. It does not recreate execution or intra-basket equity drawdown. Cost scenarios subtract extra cost per opening lot; they are not a slippage/execution rerun. Rolling performance sums the last up to 100 closed outcomes."),
 ("Correlation and market regimes","Correlation is Pearson correlation of daily booked symbol net results on common booking days; inactivity = zero. Constant series yield undefined correlation. Market regimes use 24 completed H1 bars before entry: total move >0.3% up, <-0.3% down, otherwise sideways; average range/open >0.3% volatile, otherwise quiet. This classification is heuristic. Exit reasons come from exported TP/SL/test-end comments and do not identify separate EAs."),
 ("PDF interaction and originals","Native PDF hover annotations contain chart details without JavaScript. Printed output is static. Numbered links lead to these explanations. Embedded originals preserve complete source data and charts; use the PDF viewer's attachment panel. DD price annotations read bounded M1 windows, falling back to M5. Prices are completed candle closes with their close times, not event-second quotes. Verified cache curve records contain only time, balance, equity and deposit load. Exported deal prices are labelled execution. No complete M1 or tick-history import is performed. References: MetaTrader 5 Help, Testing Report / Trading Report (metatrader5.com/en/terminal/help); GIPS Standards Handbook for Firms, Modified Dietz (gipsstandards.org).")
 }:new(){
 ("Quellen und Auswertungsumfang","Backtest- und Kontohistorie-Berichte in HTML/XLSX behalten ihre exportierten Buchungen. Originalkennzahlen werden für die Anzeige formatiert; ihre Quellwerte werden nicht ersetzt. Position-IDs haben Vorrang; mehrdeutige Zuordnungen werden gekennzeichnet. Jahreskennzahlen geschlossener Trades verwenden das Schlussjahr, monatlich gebuchte Ergebnisse das Buchungsdatum."),
 ("Gewinn, Kosten und Kontobewegungen","Deal-Netto = Gewinn + Kommission + Swap + Gebühr mit exportiertem Vorzeichen. Einzahlungen, Auszahlungen, Kredit/Bonus und sonstige Kontobuchungen bleiben separat und zählen nicht zum Handelsgewinn. Balance = Anfangsbestand + Trade-Netto + balancewirksame Kontobuchungen; Kredit verändert die Equity, nicht die Balance. Separat gebuchte Kommissionen, Gebühren und Zinsen zählen zum Handelsergebnis, nicht zu externen Geldbewegungen. Fehlende Gebührenfelder bedeuten nicht Gebührenfreiheit. Die bereinigte Ergebnislinie zieht Kontobuchungen vom tatsächlichen Kontostand ab."),
 ("Rendite und Drawdown","Tagesrenditen mit Geldbewegungen nach Modified Dietz: (Endwert - Anfangswert - Nettobuchungen) / (Anfangswert + zeitgewichtete Buchungen). Das Gewicht entspricht dem verbleibenden Zeitanteil bis Intervallende. Nicht positive Nenner werden ausgelassen. Bereinigter Drawdown aus Wert minus kumulierten Kontobuchungen: DD = bisheriger Höchststand - aktueller bereinigter Wert; DD% = DD / positiven bereinigten Höchststand × 100. Tatsächlicher Kontostand bleibt separat sichtbar. Unvollständige Exporte verhindern einen verlässlichen Kontoabgleich."),
 ("Haltezeiten und Quantile","Kalenderdauer = Vollschluss minus Einstieg. Handelsdauer zieht konfigurierte geschlossene Wochentage und die angenommene Nachtpause ab; Feiertage werden nicht erraten. Teilausstiege verwenden für den gewichteten Wert volumengewichtete Zeit. Mittelwert = Summe/n; Stichproben-Standardabweichung verwendet n-1. Angaben 'innerhalb von' verwenden den beobachteten Rang ceil(p×n), auf volle Sekunden aufgerundet. 100% entspricht der längsten beobachteten Haltedauer. Offene Trades zählen nicht zu geschlossenen Haltezeiten."),
 ("Zyklen und Testende","Ein Basket-Zyklus beginnt mit dem ersten Einstieg und endet, sobald alle Kontopositionen geschlossen sind. Einzeltrade-Modus verwendet die Positions-/Orderzuordnung. Zwangsschlüsse am Testende werden anhand der Quellkommentare erkannt; das Ende einer Kontohistorie allein ist kein Zwangsschluss. Beginn des letzten zwangsgeschlossenen Zyklus, letzter regulärer Abschluss und Testende werden in zeitbezogenen Charts markiert. Tatsächliche Verluste bleiben enthalten; die ausdrücklich bereinigte Ansicht schließt den erkannten letzten Zwangsschluss-Zyklus aus."),
 ("Equity, Kurse und Darstellung","Equity-Beobachtungen stammen bei Verfügbarkeit aus dem Original-Tester-Cache, nicht aus geschätzter Trade-Equity. Die Balance-Anzeige fasst Buchungen in konfigurierten Zeitfenstern zusammen; Berechnungen behalten Rohbuchungen. Marktkerzen verwenden bestätigte Brokerzeitregeln und die Kurswährung. Equity-Drawdown vergleicht Equity mit ihrem bisherigen Höchststand. Equity unter Balance ist eine Equity-/Balance-Differenz; durch Kredit oder weitere Anpassungen muss sie nicht genau dem unrealisierten Verlust entsprechen."),
 ("MAE / MFE","Für beobachtete Baskets: Basket-Ergebnis = gespeicherte Tester-Equity minus Balance unmittelbar vor Einstieg, einschließlich realisierter Teilausstiege und Kosten. MAE = max(0, -kleinstes beobachtetes Basket-Ergebnis); MFE = max(0, größtes beobachtetes Basket-Ergebnis). Null und Schlussnetto werden einbezogen; mindestens eine Beobachtung ist erforderlich. Datenlücken stehen im Mouseover. Beobachtete Extrema sind keine exakten Tick-Extrema. Einzeltrade-H1-Auswertung nutzt nur vollständig abgedeckte Innenkerzen und misst prozentuale Kursbewegung, keine Tick-Extrema in Geld."),
 ("Zeitmuster und Balken","Heatmap-Mouseover gilt für das konkrete Wochentag-/Stundenfeld. Anteil langer Zyklen = regulär abgeschlossene Zyklen über Grenzwert / alle regulären Starts im Feld × 100; >24 h nutzt dieselbe Zeitbasis. Testende-Zyklen sind aus dieser Quote ausgeschlossen. Gestapelte Gewinn-/Verlustbalken zeigen Gewinne plus absolute Verluste, nicht Netto als Höhe. Breite Balken zeigen Gewinn, Verlust und Netto, schmale Balken Netto im Mouseover."),
 ("Risikokennzahlen","Profitfaktor = positives Netto / Betrag negativen Nettos; ohne Verluste nicht definiert. Trefferquote = Gewinner / alle abgeschlossenen Beobachtungen. Sharpe = mittlere Tagesrendite / Stichproben-Standardabweichung × √252, risikofrei 0. Sortino verwendet negative Tagesrenditen gegen 0 × √252. Ulcer-Index = Quadratwurzel des Mittels quadrierter gespeicherter DD-Prozente, nicht zeitgewichtet. Calmar = CAGR / maximalen Equity-DD; bei Geldbewegungen ohne belastbare CAGR ausgelassen."),
 ("Sensitivität und Simulation","Gewinnkonzentration entfernt größte Gewinnbeobachtungen nur als Sensitivitätsprüfung. Monte Carlo zieht ganze Tagesblöcke realisierter Ergebnisse mit Zurücklegen, 600 Läufe, reproduzierbarer Seed 12345. Keine neue Ausführung und kein intra-Basket-Equity-DD. Kosten-Szenarien ziehen Zusatzkosten je Einstiegs-Lot ab; kein neuer Slippage-/Ausführungsbacktest. Rollierende Performance summiert die letzten bis zu 100 abgeschlossenen Ergebnisse."),
 ("Korrelation und Marktphasen","Pearson-Korrelation verwendet täglich gebuchtes Symbolnetto an gemeinsamen Buchungstagen; fehlende Aktivität = 0. Konstante Reihen haben keine definierte Korrelation. Marktphasen nutzen 24 abgeschlossene H1-Kerzen vor Einstieg: Bewegung >0,3% aufwärts, <-0,3% abwärts, sonst seitwärts; mittlere Spanne/Eröffnung >0,3% volatil, sonst ruhig. Diese Einteilung ist heuristisch. Schließungsgründe stammen aus exportierten TP-/SL-/Testende-Kommentaren und sind keine EA-Trennung."),
 ("PDF-Bedienung und Originaldateien","Native PDF-Mouseover enthalten Chartdetails ohne JavaScript. Beim Drucken bleibt die Darstellung statisch. Nummerierte Verweise führen zu diesen Erklärungen. Eingebettete Originale behalten vollständige Quelldaten und Grafiken; erreichbar über den Anhangsbereich des PDF-Programms. DD-Kursangaben verwenden gezielte kurze M1-Zeitfenster, ersatzweise M5. Angegeben wird der bereits abgeschlossene Kerzenschluss samt Uhrzeit, kein Kurs zur Ereignissekunde. Der geprüfte Cache-Kurvenpunkt enthält nur Zeit, Balance, Equity und Kontobelastung. Exportierte Dealpreise sind als Ausführung bezeichnet. Es erfolgt kein vollständiger M1- oder Tickhistorienimport. Fachliche Referenzen: MetaTrader 5 Help, Testing Report / Trading Report (metatrader5.com/en/terminal/help); GIPS Standards Handbook for Firms, Modified Dietz (gipsstandards.org).")
 };
}
