using System.Globalization;
using System.Text.RegularExpressions;
namespace BacktestAnalyzer;
public static class Localization
{
 public static bool English {get;set;}
 public static CultureInfo Culture=>CultureInfo.GetCultureInfo(English?"en-US":"de-AT");
 static readonly Dictionary<string,string> Terms=new(StringComparer.OrdinalIgnoreCase)
 {
  ["Marktkurs im Detail"]="Market detail",["Testprofil"]="Test profile",["Brokerzeiten direkt"]="direct broker timestamps",
  ["Einstellungen"]="Settings",["Analyseoptionen"]="Analysis options",["Export & Zusatzfunktionen"]="Export & additional features",["Marktkurs"]="Market price",["Übernehmen"]="Apply",["Marktkerzen"]="Market candles",["Kurse nicht verfügbar"]="Prices unavailable",["dichte Ansicht: OHLC pro Pixelgruppe"]="dense view: OHLC per pixel group",["Zeitregel unbestätigt"]="time rule unconfirmed",["rechte Achse"]="right axis",["Kerzen im Zeitfenster"]="candles in time window",["Zeitfenster"]="Time window",
  ["Handelsdauer · geschlossene Wochenendtage und pauschale Nachtpause abgezogen"]="Trading duration · closed weekend days and assumed overnight break excluded",
  ["Handelsdauer · geschlossene Wochenendtage und Nachtpause abgezogen"]="Trading duration · closed weekend days and overnight break excluded",
  ["Handelsdauer"]="Trading duration",["Handelsstunden"]="trading hours",["Nachtpause"]="Overnight break",["Schließzeit"]="Closing time",["Offene Positionen"]="Open positions",["Offene Lots"]="Open lots",["Margin-Auslastung"]="Margin utilization",["Gesamt"]="Total",["Analyse speichern"]="Save analysis",["Backtests vergleichen"]="Compare backtests",["Backtest-Vergleich"]="Backtest comparison",["Backtest A laden"]="Load backtest A",["Backtest B laden"]="Load backtest B",["Differenz"]="Difference",["Kennzahl"]="Metric",["Gewinn-/Verlustbetrag"]="Profit/loss amount",["größerer Betrag"]="larger amount",["kleinerer Betrag"]="smaller amount",["gestrichelt"]="dashed",["Fläche"]="Fill",["Kalenderdauer"]="Calendar duration",["pauschale Nachtpause"]="assumed overnight break",["geschlossene Wochenendtage"]="closed weekend days",
  ["Jegliche Haftung vollständig ausgeschlossen · Keine Gewähr für Vollständigkeit und Richtigkeit · Berichte/Analysen können Fehler enthalten · Keine Verbindung zu MetaQuotes · MetaTrader: Marken/Urheberrechte MetaQuotes Ltd"]="All liability excluded · No warranty of completeness or accuracy · Reports/analyses may contain errors · No affiliation with MetaQuotes · MetaTrader: trademarks/copyright MetaQuotes Ltd",
  ["Gesamtübersicht"]="Overall overview",["Gesamtauswertung"]="Overall analysis",["Gesamter Test"]="Entire test",["Gesamtbericht"]="Overall report",["Nur Jahresdetails"]="Yearly details only",["Gesamt mit Jahresdetails"]="Overall and yearly details",["Jahresauswertung"]="Yearly analysis",["Gesamttest"]="Entire test",["Settings"]="Settings",
  ["Übersicht"]="Overview",["Haltezeiten"]="Holding times",["Zeitmuster"]="Time patterns",["Datenprüfung"]="Data audit",["Bericht importieren"]="Import report",["MT5 finden"]="Find MT5",["PDF erstellen"]="Create PDF",["Interaktiver HTML-Report"]="Interactive HTML report",["Trades als CSV"]="Export trades as CSV",["Passenden Cache ergänzen"]="Attach matching cache",["Nur eindeutige History"]="Confirmed history only",["P/L-Konsistenzmodell"]="P/L consistency model",
  ["Samstag Handelstag"]="Saturday is a trading day",["Sonntag Handelstag"]="Sunday is a trading day",["Wochenende automatisch erkennen"]="Detect weekend activity",["Geschlossene Tage"]="Closed days",["Auto: Wochenendbuchungen"]="Auto: weekend transactions",
  ["Alle Symbole"]="All symbols",["Prozent"]="Percentage",["Anzahl"]="Count",["Trade-Anhang"]="Trade appendix",["Haltezeit: Kalender"]="Holding time: calendar",["Haltezeit: ohne Sa/So"]="Holding time: closed days excluded",["Rohbuchungen"]="Raw transactions",["Quick Report (A4 quer)"]="Quick report (A4 landscape)",["Detailanalyse (A4 hoch)"]="Detailed report (A4 portrait)",
  ["Ababgeschlossene Trades"]="Closed trades",["Abgeschlossene Trades"]="Closed trades",["Abgeschlossene Zyklen"]="Completed cycles",["Durchschnittliche Haltezeit"]="Average holding time",["Mittlere Haltezeit (50 %)"]="Median holding time (50%)",["Längste Haltezeit"]="Longest holding time",["Kürzeste Haltezeit"]="Shortest holding time",["Durchschnitt"]="Average",["Minimum"]="Minimum",["Maximum"]="Maximum",["Median"]="Median",["95. Perzentil"]="95th percentile",["Streuung"]="Dispersion",
  ["Gehandeltes Einstiegsvolumen"]="Traded entry volume",["Lots (Einstieg)"]="Lots (entry)",["Gesamtgewinn"]="Total profit",["Um letzten Zyklus bereinigt"]="Adjusted for final cycle",["tatsächliches Ergebnis"]="actual result",["Testende-Zyklus separat"]="Test-end cycle separately",["Testende-Zyklus"]="Test-end cycle",["Testende-Zyklen"]="Test-end cycles",["Testende"]="Test end",["Anfangsbestand"]="Opening balance",["Letzter exportierter Kontostand"]="Last exported balance",["Netto aus gebuchten Deals"]="Net profit from booked deals",["Brutto aus Deals"]="Gross deal result",["Kommission"]="Commission",["Komm."]="Comm.",["Separate Gebühren"]="Separate fees",["nicht exportiert"]="not exported",["nicht verfügbar"]="unavailable",["nicht definiert"]="undefined",["keine"]="none",
  ["Gewinner"]="Winners",["Verlierer"]="Losers",["Gewinne und Verluste"]="Profits and losses",["Gewinn"]="Profit",["Verlust"]="Loss",["Gewinne"]="Profits",["Verluste"]="Losses",["Trefferquote"]="Win rate",["Profitfaktor"]="Profit factor",["Erwartetes Netto je Trade"]="Expected net per trade",["Bestes / schlechtestes Trade"]="Best / worst trade",["Schlussjahr-Kohorte"]="closing-year cohort",["Kontowährung"]="Account currency",["Kontostand"]="Account balance",["Kontobelastung"]="Deposit load",["Rohbuchungs-Balance-DD"]="Raw-booking balance DD",["Prüfwert"]="audit value",["Bezugs-Höchststand"]="reference peak",["Zeitpunkt"]="Timestamp",["in Prozent"]="in percent",["in Geld"]="in money",
  ["Ordereröffnungen"]="Order openings",["Einstiegszeit"]="entry time",["Einstiegsstunde"]="entry hour",["Einstiegswochentag"]="entry weekday",["Startstunde"]="start hour",["Startwochentag"]="start weekday",["Wochentag"]="Weekday",["Tageszeit"]="Time of day",["Monatsergebnis"]="Monthly result",["Monatsübersicht"]="Monthly overview",["Monat"]="Month",["Buchungsmonat"]="Booking month",["Jahressumme"]="Year total",["Summe"]="Total",["Fortsetzung"]="Continuation",["Jänner"]="January",["Januar"]="January",["Februar"]="February",["März"]="March",["April"]="April",["Mai"]="May",["Juni"]="June",["Juli"]="July",["August"]="August",["September"]="September",["Oktober"]="October",["November"]="November",["Dezember"]="December",
  ["Montag"]="Monday",["Dienstag"]="Tuesday",["Mittwoch"]="Wednesday",["Donnerstag"]="Thursday",["Freitag"]="Friday",["Samstag"]="Saturday",["Sonntag"]="Sunday",["Mo"]="Mon",["Di"]="Tue",["Mi"]="Wed",["Do"]="Thu",["Fr"]="Fri",["Sa"]="Sat",["So"]="Sun",["Jan"]="Jan",["Feb"]="Feb",["Mär"]="Mar",["Jun"]="Jun",["Jul"]="Jul",["Okt"]="Oct",["Dez"]="Dec",
  ["Haltezeitverteilung"]="Holding-time distribution",["Haltezeit"]="Holding time",["Haltedauer"]="Holding duration",["Kurzzeit"]="Short duration",["Langzeit"]="Long duration",["Langzeitdetail"]="Long-duration detail",["Kurzzeit- und Langzeitdetail"]="Short- and long-duration details",["Kalender-Haltedauer inklusive Wochenenden"]="Calendar duration including weekends",["Kalender-Haltezeit inklusive Wochenenden"]="Calendar holding time including weekends",["Kalenderzeit"]="Calendar time",["logarithmische Zeitachse"]="logarithmic time axis",["Minuten"]="Minutes",["Stunden"]="Hours",["Tage"]="Days",["Uhr"]="h",["Intervalle"]="Intervals",["Wie schnell werden Trades geschlossen?"]="How quickly are trades closed?",["innerhalb von"]="within",["geschlossen nach"]="closed within",["ohne Sa/So"]="excluding closed weekend days",["geschlossen"]="closed",["abgeschlossen"]="completed",["offen am Abschnittsende"]="open at period end",
  ["Tageskurven"]="Weekday curves",["Startzeit-Heatmap"]="Start-time heatmap",["Zyklen"]="Cycles",["Serien"]="Cycles",["Lange Handelszyklen"]="Long trading cycles",["10 ungünstigste Startzeitfenster"]="10 highest long-cycle start-time rates",["wenige Fälle"]="small sample",["reguläre"]="regular",["vollständige"]="complete",["lange"]="long",["Starts"]="Starts",["Anteil"]="Share",["Blau"]="Blue",["Orange"]="Orange",["alle Positionen"]="all positions",["erster Einstieg"]="first entry",["Zyklusergebnis"]="Cycle result",["Start-Wochentag und Uhrzeit"]="Start weekday and hour",["Startzeit"]="Start time",["Stunde"]="Hour",["Broker-Zeit"]="Broker time",
  ["Backtestprofil"]="Backtest profile",["TESTPROFIL"]="TEST PROFILE",["Datenqualität"]="Data quality",["Historienqualität"]="History quality",["Qualität der Historie"]="History quality",["Qualität"]="Quality",["Verwendete Ticks"]="Ticks used",["Zeitraum / Periode"]="Period / timeframe",["Verzögerung"]="Execution delay",["Tester-Spread"]="Tester spread",["Tester-Slippage"]="Tester slippage",["Balken / Symbole"]="Bars / symbols",["Balken"]="Bars",["Symbole"]="Symbols",["Kontowährung / Hebel"]="Account currency / leverage",["Hebel"]="Leverage",["Jeder Tick anhand realer Ticks"]="Every tick based on real ticks",["echte Ticks"]="real ticks",["Tickmodell"]="Tick model",["fest"]="fixed",["bis"]="to",
  ["Originalkennzahlen"]="Original metrics",["Originalangaben aus MetaTrader (nicht neu berechnet)"]="Original MetaTrader values (not recalculated)",["Alle Originalkennzahlen"]="All original metrics",["Strategieparameter"]="Strategy inputs",["Originalwerte"]="Original values",["Originalauswertungen"]="Original-related analyses",["Originaldateien"]="Original files",["Originalgrafiken"]="Original charts",["vollständige Historie"]="complete history",["Vollständige Originaldateien im PDF enthalten"]="Complete original files embedded in PDF",["Importhinweise"]="Import notes",["Methodik"]="Methodology",["Eigene Berechnungen"]="Our calculations",["Standardabweichung (Stichprobe)"]="Standard deviation (sample)",["Volumengewichtete Teilausstiegsdauer"]="Volume-weighted partial-exit duration",["Offene Positionseinheiten am Abschnittsende"]="Open position units at period end",["Kontoergebnis"]="Account result",["Kosten und Risiko"]="Costs and risk",["Detailanalyse"]="Detailed analysis",["Kennzahl"]="Metric",["Vergleich"]="Comparison",["Verteilung und Streuung"]="Distribution and dispersion",["Zusammenhang"]="Relationship",["Ergebnis und Zeit"]="Result and time",
  ["Haftung ausgeschlossen, soweit gesetzlich zulässig"]="Liability excluded to the extent permitted by law",["Keine Verbindung zu MetaQuotes"]="No affiliation with MetaQuotes",["Marken/Urheberrechte"]="Trademarks/copyright",["Fehler möglich"]="Errors possible",["Keine Anlageberatung"]="No investment advice",["lokal und offline"]="local and offline",["unabhängiger Analyzer"]="independent analyzer",["Import läuft"]="Importing",["Dateisuche läuft"]="Searching files",["Aktualisieren"]="Refresh",["Ausgewählten Bericht importieren"]="Import selected report",["Nur geöffnete MT5"]="Running MT5 instances only",["Daten-/Exportordner wählen"]="Choose data/export folder",["Bericht"]="Report",["Berichte"]="Reports",["PDF gespeichert"]="PDF saved",["Import fehlgeschlagen"]="Import failed",["Importprüfung"]="Import validation",["Richtung"]="Side",["Einstieg"]="Entry",["Vollschluss"]="Final close",["Zuordnung"]="Matching",["ausgewählte"]="selected",["ausgewählten"]="selected",["aller Trades"]="of all trades",["eigene Y-Skala je Detailansicht"]="individual Y scale per detail view",
  ["Originalkennzahlen bleiben separat erhalten. Buchungsjahr und Schlussjahr werden unterschieden; echte Kontobuchungen werden nicht entfernt."]="Original metrics are retained separately. Booking year and closing year are distinguished; actual account transactions are not removed.",
  ["Gesamtauswertung mit vollständigen Jahresabschnitten. Haltezeiten mit echten Position-IDs, sofern ein passender Tester-Cache vorliegt."]="Overall analysis with complete yearly sections. Holding times use actual position IDs when a matching tester cache is available.",
  ["Balance-Buchungen werden für die Anzeige standardmäßig in festen 60-s-Fenstern zusammengefasst. Equity und Equity-DD bleiben ungeglättet. Rohdaten und Kostenberechnungen bleiben erhalten. Fehlende Testprofilangaben werden nicht aus Qualitätsprozenten erraten."]="Balance transactions are displayed in fixed 60-second windows by default. Equity and equity drawdown remain unsmoothed. Raw data and costs are retained. Missing test settings are not inferred from quality percentages.",
  ["In Acrobat: Anhänge öffnen. Die Originaldateien enthalten sämtliche Order-/Deal-Zeilen, Originalgrafiken und Angaben unverändert. Neu gestaltete Tabellen und Diagramme stehen im Bericht; die Anhänge sichern die vollständige Originalinformation."]="In Acrobat, open Attachments. Original files retain every order/deal row, original chart and original value. Redesigned tables and charts are included in the report; attachments preserve the complete source information.",
  ["Equity-DD = bisheriger Equity-Höchststand minus aktuelle Equity. Balance minus Equity ist der offene Verlust, nicht derselbe Drawdown. Jahres-DD bezieht sich auf den Equity-Höchststand innerhalb des Jahres einschließlich übernommenem Anfangswert. Die Cache-Kurve enthält gespeicherte Beobachtungen, keine vollständige Tickhistorie."]="Equity drawdown is the previous equity peak minus current equity. Balance minus equity is floating loss, a different measure. Annual drawdown uses the within-year equity peak including the carried opening observation. Cached curves contain saved observations, not a complete tick history.",
  ["Zusammenhänge sind beschreibend. Ein höherer Gewinn bei längerer Haltezeit belegt keine Ursache. Bei Teilausstiegen wird das Ergebnis dem Vollschluss des Trades zugeordnet."]="Relationships are descriptive. Higher profits with longer holding times do not establish causation. Partial-exit results are assigned to the trade's final close.",
  ["Keine erkennbare Testende-Schließung in diesem Abschnitt."]="No identifiable test-end closure in this period.",
  ["Trades verstehen. Haltezeiten sichtbar machen.  |  BETA"]="Understand trades. See holding times. | BETA"
 };
 static readonly Regex Pattern=new(string.Join("|",Terms.Keys.OrderByDescending(k=>k.Length).Select(k=>"(?<![\\p{L}\\p{N}_])"+Regex.Escape(k)+"(?![\\p{L}\\p{N}_])")),RegexOptions.IgnoreCase|RegexOptions.Compiled);
 public static string T(string value)=>English?Pattern.Replace(value,m=>Terms[m.Value]):value;
}
