using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
namespace BacktestAnalyzer;
public sealed partial class MainWindow
{
    ControlTemplate ComboTemplate()=> (ControlTemplate)System.Windows.Markup.XamlReader.Parse("""
    <ControlTemplate xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" TargetType="ComboBox">
      <Grid><ToggleButton Focusable="False" IsChecked="{Binding IsDropDownOpen, Mode=TwoWay, RelativeSource={RelativeSource TemplatedParent}}"><ToggleButton.Template><ControlTemplate TargetType="ToggleButton"><Border Background="{Binding Background,RelativeSource={RelativeSource AncestorType=ComboBox}}" BorderBrush="{Binding BorderBrush,RelativeSource={RelativeSource AncestorType=ComboBox}}" BorderThickness="1" CornerRadius="5"><TextBlock Text="⌄" HorizontalAlignment="Right" VerticalAlignment="Center" Margin="0,0,8,0" Foreground="{Binding Foreground,RelativeSource={RelativeSource AncestorType=ComboBox}}"/></Border></ControlTemplate></ToggleButton.Template></ToggleButton><ContentPresenter IsHitTestVisible="False" Content="{TemplateBinding SelectionBoxItem}" ContentTemplate="{TemplateBinding SelectionBoxItemTemplate}" Margin="8,7,25,7" VerticalAlignment="Center" TextElement.Foreground="{TemplateBinding Foreground}"/><Popup IsOpen="{TemplateBinding IsDropDownOpen}" Placement="Bottom" AllowsTransparency="True" Focusable="False"><Border Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="1" MinWidth="{Binding ActualWidth,RelativeSource={RelativeSource TemplatedParent}}"><ScrollViewer MaxHeight="320"><ItemsPresenter/></ScrollViewer></Border></Popup></Grid>
    </ControlTemplate>
    """);
    bool navCollapsed;StackPanel? settingsContent;
    UIElement ThemeIcon()
    {
        var g=new DrawingGroup();using(var dc=g.Open()){var pen=new Pen(B(P.Positive),1.5);dc.DrawEllipse(null,pen,new Point(9,9),4,4);for(int i=0;i<8;i++){double a=i*Math.PI/4;dc.DrawLine(pen,new Point(9+6*Math.Cos(a),9+6*Math.Sin(a)),new Point(9+8*Math.Cos(a),9+8*Math.Sin(a)));}dc.DrawGeometry(B(P.Positive),null,Geometry.Parse("M14,4 C12,9 15,14 20,13 C16,18 10,16 10,11 C10,8 11,6 14,4 Z"));}return new Image{Source=new DrawingImage(g),Width=21,Height=21};
    }
    TextBox Field(string value)=>new(){Text=value,Padding=new Thickness(8),Margin=new Thickness(0,3,0,8),Background=B(P.Surface),Foreground=B(P.Ink),BorderBrush=B(P.Line)};
    UIElement LongThreshold()
    {
        var row=new WrapPanel();row.Children.Add(Text(Localization.English?"Long cycles above (hours)":"Lange Zyklen über (Stunden)",13));var input=Field(Current!.LongSeriesHours.ToString(CultureInfo.InvariantCulture));input.Width=90;row.Children.Add(input);row.Children.Add(Button("Übernehmen",()=>{if(double.TryParse(input.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var h)&&double.IsFinite(h)&&h>0&&h<=87600){Current.LongSeriesHours=h;Render();}else MessageBox.Show(Localization.English?"Enter a positive number of hours (max 87600).":"Positive Stundenzahl eingeben (max. 87600).");}));return row;
    }
    void ShowSettings()
    {
        var w=new Window{Owner=this,Title=Localization.English?"Settings":"Einstellungen",Width=850,Height=780,Background=B(P.Background),Foreground=B(P.Ink),WindowStartupLocation=WindowStartupLocation.CenterOwner};var tabs=new TabControl{Margin=new Thickness(18),Background=B(P.Surface),Foreground=B(P.Ink)};
        var general=new StackPanel{Margin=new Thickness(16)};general.Children.Add(Button("MT5 finden",()=>ChooseTerminal()));general.Children.Add(Button("Bericht importieren",()=>ChooseFile()));if(settingsContent!=null){var parent=settingsContent.Parent as Panel;parent?.Children.Remove(settingsContent);general.Children.Add(settingsContent);}
        if(Current!=null){general.Children.Add(Text(Localization.English?"Strategy type":"Strategietyp",13,true));general.Children.Add(Select(new[]{"Basket","Einzelorder"},Current.StrategyMode=="single"?"Einzelorder":"Basket",v=>Current.StrategyMode=v=="Einzelorder"?"single":"basket"));general.Children.Add(LongThreshold());}tabs.Items.Add(new TabItem{Header=Localization.English?"Analysis & export":"Analyse & Export",Content=new ScrollViewer{Content=general,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}});
        if(Current!=null)tabs.Items.Add(new TabItem{Header=Localization.English?"Market & time":"Marktdaten & Zeit",Content=new ScrollViewer{Content=MarketSettings(),VerticalScrollBarVisibility=ScrollBarVisibility.Auto}});
        w.Content=tabs;w.ShowDialog();Render();
    }
    UIElement MarketSettings()
    {
        TextBox? providerSymbolInput=null;var r=Current!;var panel=new StackPanel{Margin=new Thickness(20)};
        panel.Children.Add(Text(Localization.English?"Import candles directly from MT5":"Kerzen direkt aus MT5 abrufen",18,true));
        var terminals=Mt5Market.Terminals();string terminal=terminals.Contains(r.MarketTerminalPath)?r.MarketTerminalPath:terminals.FirstOrDefault()??"";var terminalBox=Select(terminals,terminal,v=>terminal=v);panel.Children.Add(terminalBox);panel.Children.Add(Button(Localization.English?"Choose MT5 terminal":"MT5-Programm wählen",()=>{var file=new OpenFileDialog{Filter="MT5|terminal64.exe"};if(file.ShowDialog()==true){terminal=file.FileName;terminalBox.ItemsSource=new[]{terminal};terminalBox.SelectedIndex=0;}}));
        var available=Text(Localization.English?"Load available symbols, then select the exact standard or custom instrument.":"Verfügbare Kurse laden und das genaue Standard- oder Custom-Symbol auswählen.",12);panel.Children.Add(Panel(available,12));
        var list=new ComboBox{DisplayMemberPath="Label",Background=B(P.Surface),Foreground=B(P.Ink),Padding=new Thickness(8),Margin=new Thickness(0,4,0,12)};list.Template=ComboTemplate();panel.Children.Add(list);
        var find=Button(Localization.English?"Find available courses":"Verfügbare Kurse finden",()=>{});find.Click+=async(_,_)=>{find.IsEnabled=false;try{var all=await Mt5Market.Symbols(terminal);list.ItemsSource=all;list.SelectedItem=all.FirstOrDefault(s=>s.Name==r.MarketMt5Symbol);list.SelectedItem??=all.FirstOrDefault(s=>s.Name==r.MarketBrokerSymbol);available.Text=$"{all.Count} Symbole · {all.Count(s=>s.Custom)} Custom · "+(Localization.English?"select below":"unten auswählen");}catch(Exception ex){available.Text=ex.Message;}finally{find.IsEnabled=true;}};panel.Children.Add(find);
        var mtLoad=Button(Localization.English?"Load candles from MT5":"Kerzen aus MT5 laden",()=>{},true);mtLoad.Click+=async(_,_)=>{if(list.SelectedItem is not Mt5Symbol selected){available.Text=Localization.English?"Select an available symbol first.":"Zuerst ein verfügbares Kurssymbol auswählen.";return;}mtLoad.IsEnabled=false;available.Text=Localization.English?"Reading H1 history...":"H1-Historie wird ausgelesen …";try{await Mt5Market.Load(r,terminal,selected.Name);if(providerSymbolInput!=null)providerSymbolInput.Text=r.MarketSymbol;available.Text=$"{selected.Name}"+(selected.Custom?" · Custom":"")+$" · {r.MarketBars.Count:N0} H1 · {r.MarketBars[0].Utc:dd.MM.yyyy} – {r.MarketBars[^1].Utc:dd.MM.yyyy}";}catch(Exception ex){available.Text=ex.Message;}finally{mtLoad.IsEnabled=true;}};panel.Children.Add(mtLoad);
        panel.Children.Add(Text(Localization.English?"External data / symbol mapping":"Externe Daten / Symbolzuordnung",18,true));
        panel.Children.Add(Text(Localization.English?"Backtest symbol":"Symbol im Backtest",12));var symbols=r.Deals.Select(d=>d.Symbol).Where(s=>s.Length>0).Distinct().ToList();if(r.MarketBrokerSymbol.Length==0)r.MarketBrokerSymbol=symbols.FirstOrDefault()??r.Find("Symbol");panel.Children.Add(Select(symbols,r.MarketBrokerSymbol,v=>r.MarketBrokerSymbol=v));
        panel.Children.Add(Text(Localization.English?"Source symbol (Dukascopy)":"Datenquellen-Symbol (Dukascopy)",12));var symbolInput=Field(r.MarketSymbol);providerSymbolInput=symbolInput;panel.Children.Add(symbolInput);panel.Children.Add(Select(MarketData.Symbols,r.MarketSymbol,v=>symbolInput.Text=v));
        panel.Children.Add(Text(Localization.English?"CSV: Time,Open,High,Low,Close; prices with decimal point. CSV source UTC offset:":"CSV: Time,Open,High,Low,Close; Preise mit Dezimalpunkt. UTC-Verschiebung der CSV:",10,false,P.Muted));var csvOffset=Field("0");panel.Children.Add(csvOffset);
        var result=Text(r.MarketBars.Count+" H1 · "+r.MarketSource+" · "+r.MarketStatus,12);panel.Children.Add(result);
        void Mapping(){var next=symbolInput.Text.Trim().ToUpperInvariant();if(next!=r.MarketLoadedSymbol){r.MarketBars=new();r.MarketSource="";}r.MarketSymbol=next;}
        panel.Children.Add(Button(Localization.English?"Apply symbol mapping":"Symbolzuordnung übernehmen",()=>{Mapping();result.Text=r.MarketBrokerSymbol+" → "+r.MarketSymbol;}));
        var load=Button(Localization.English?"Download historical data":"Historische Kurse laden",()=>{},true);load.Click+=async(_,_)=>{Mapping();load.IsEnabled=false;try{await MarketData.Load(r,new Progress<string>(s=>result.Text=s));result.Text=$"{r.MarketBars.Count:N0} H1 · {r.MarketSource} · {r.MarketStatus}";r.MarketEnabled=true;}catch(Exception ex){r.MarketStatus=ex.Message;result.Text=ex.Message;}finally{load.IsEnabled=true;}};panel.Children.Add(load);
        panel.Children.Add(Button(Localization.English?"Import candle CSV":"Kerzen-CSV importieren",()=>{var picker=new OpenFileDialog{Filter="CSV|*.csv"};if(picker.ShowDialog()!=true)return;try{Mapping();MarketData.ImportCsv(r,picker.FileName,(int)(Parser.Number(csvOffset.Text)*60));r.MarketEnabled=true;result.Text=r.MarketBars.Count+" · "+r.MarketSource;}catch(Exception ex){result.Text=ex.Message;}}));
        panel.Children.Add(Check(Localization.English?"Market candles in app and PDF":"Marktkerzen in App und PDF",r.MarketEnabled,v=>r.MarketEnabled=v));panel.Children.Add(Select(new[]{"Auto","H1","H2","H4","H8","H12","D1","D2","D4","W1","MN1"},r.MarketInterval,v=>r.MarketInterval=v=="T1"?"D1":v));
        panel.Children.Add(Text(Localization.English?"Broker time calculator":"Berechnungshilfe Brokerzeit",18,true));panel.Children.Add(Text(Localization.English?"Local date/time":"Datum / Uhrzeit bei dir",12));var local=Field(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));panel.Children.Add(local);panel.Children.Add(Text(Localization.English?"Server date/time (same moment)":"Server-Datum / Uhrzeit (derselbe Moment)",12));var server=Field(DateTime.Now.AddHours(1).ToString("yyyy-MM-dd HH:mm:ss"));panel.Children.Add(server);
        var zone="W. Europe Standard Time";panel.Children.Add(Select(new[]{"W. Europe Standard Time","UTC","GMT Standard Time","Eastern Standard Time"},zone,v=>zone=v));var timeResult=Text("UTC"+(r.BrokerUtcOffsetMinutes>=0?"+":"")+(r.BrokerUtcOffsetMinutes/60d).ToString("0.##"),13,true);panel.Children.Add(timeResult);
        panel.Children.Add(Button(Localization.English?"Calculate & apply":"Berechnen & anwenden",()=>{try{var l=DateTime.ParseExact(local.Text,"yyyy-MM-dd HH:mm:ss",CultureInfo.InvariantCulture);var s=DateTime.ParseExact(server.Text,"yyyy-MM-dd HH:mm:ss",CultureInfo.InvariantCulture);r.BrokerUtcOffsetMinutes=MarketData.CalculateOffset(l,s,TimeZoneInfo.FindSystemTimeZoneById(zone));r.BrokerTimeRule="Fixed";r.BrokerTimeConfirmed=false;timeResult.Text=$"UTC{r.BrokerUtcOffsetMinutes/60d:+0.##;-0.##;0} · angewendet / applied";}catch(Exception ex){timeResult.Text=ex.Message;}}));
        panel.Children.Add(Text(Localization.English?"Historical time rule":"Historische Zeitregel",14,true));var rule=Select(new[]{"Fixed","EU","US"},r.BrokerTimeRule,v=>r.BrokerTimeRule=v);panel.Children.Add(rule);panel.Children.Add(Text(Localization.English?"Winter UTC offset (hours); EU/US add one hour during DST":"Winter-UTC-Offset (Stunden); EU/US addiert eine Sommerzeitstunde",11));var winter=Field((r.BrokerWinterOffsetMinutes/60d).ToString(CultureInfo.InvariantCulture));panel.Children.Add(winter);panel.Children.Add(Button("Übernehmen",()=>{try{var value=Parser.Number(winter.Text);if(value < -12||value>14)throw new ArgumentException("UTC: -12 bis +14");r.BrokerWinterOffsetMinutes=(int)(value*60);timeResult.Text="Zeitregel übernommen / Time rule applied";}catch(Exception ex){timeResult.Text=ex.Message;}}));panel.Children.Add(Check(Localization.English?"Historical broker rule confirmed":"Historische Broker-Zeitregel bestätigt",r.BrokerTimeConfirmed,v=>r.BrokerTimeConfirmed=v));panel.Children.Add(Text(Localization.English?"Today's offset does not determine historical DST. External quotes are market context, not original execution prices.":"Die heutige Differenz bestimmt keine historische Sommerzeitregel. Fremdkurse zeigen den Markt, nicht die originalen Ausführungspreise.",10,false,P.Muted));return panel;
    }
}
